language: go

go:
  - "1.10"

sudo: required

services:
  - docker

install:
  - mkdir ${TRAVIS_HOME}/gopath/src/github.com/boz && mv ${TRAVIS_HOME}/gopath/src/github.com/qiniu-ava/kail ${TRAVIS_HOME}/gopath/src/github.com/boz/kail
  - cd ${TRAVIS_HOME}/gopath/src/github.com/boz/kail && make install-deps

script: |
  make test-full
